# Generated by Django 4.2.7 on 2023-11-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_userfollowing_post_userfollowing_unique_followers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.CheckConstraint(check=models.Q(('user_id', models.F('following_user_id')), _negated=True), name="User can't follow itself"),
        ),
    ]
