# Generated by Django 4.2.7 on 2023-11-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_userfollowing_user_can_t_follow_itself'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pots_text',
            new_name='post_text',
        ),
    ]
